apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bank-chart.fullname" . }}-secrets
  labels:
    {{- include "bank-chart.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-user: {{ .Values.global.postgresql.user | b64enc }}
  postgres-password: {{ .Values.global.postgresql.password | b64enc }}
  account-client-secret: {{ .Values.oauth.account_client_secret | b64enc }}
  cash-client-secret: {{ .Values.oauth.cash_client_secret | b64enc }}
  transfer-client-secret: {{ .Values.oauth.transfer_client_secret | b64enc }}
  keycloak-admin: {{ .Values.global.keycloak.admin | b64enc }}
  keycloak-admin-password: {{ .Values.global.keycloak.adminPassword | b64enc }}