apiVersion: v1
kind: Service
metadata:
  name: cash-service
  labels:
    app: cash-service
    {{- include "cash-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cash-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}