spring:
  application:
    name: notification-service
  config:
    import: configserver:http://127.0.0.1:8888
  profiles:
    active: dev
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5434/postgres?currentSchema=notification
#    username: postgres
#    password: password
#  liquibase:
#    url: jdbc:postgresql://localhost:5434/postgres?currentSchema=notification
#    user: postgres
#    password: password
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: notification
#    liquibase-schema: public
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/master

server:
  port: 8084