services:
  #### Infrastructure ####
  config-server:
    build: ./config-server
    image: config-server:latest
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    networks:
      - app-network

  gateway:
    build: ./gateway
    image: gateway:latest
    container_name: gateway
    restart: always
    ports:
      - "9080:9080"
    depends_on:
      discovery-server:
        condition: service_started
    networks:
      - app-network

  discovery-server:
    build: ./discovery-server
    image: discovery-server:latest
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - app-network

  account-db:
    image: postgres:15-alpine
    container_name: postgres-bank-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  notification-db:
    image: postgres:15-alpine
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:8.1.0
    restart: always
    ports:
      - "29092:29092"
    environment:
      CLUSTER_ID: ZETVJENWRjaECDUEExP_eg
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # КРИТИЧЕСКИ ВАЖНО для 1 брокера:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Дополнительные настройки для single-node:
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    depends_on:
      - kafka
    ports:
      - "8180:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: true

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:3.5
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash
    restart: always
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/logs
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network

  #### Security infrastructure ####
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    restart: always
    environment:
      KC_HTTP_PORT: 8090
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres_db:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8090:8090"
    command: ["start-dev"]
    depends_on:
      account-db:
        condition: service_started
    networks:
      - app-network
      - security-network

  keycloak-postgres:
    image: postgres:15-alpine
    container_name: keycloak_postgres_db
    restart:  always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      security-network:
        aliases:
          - keycloak-postgres

#### Services ####
  bank-front:
    build: ./bank-front
    image: online-store:latest
    container_name: bank-front
    restart: no
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      # Настройки клиентского сервиса для получения токенов из keycloak
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_ID: ${MARKET_CLIENT_ID}
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_SECRET: ${MARKET_CLIENT_SECRET}
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8090/realms/master
    depends_on:
      account-service:
        condition: service_started
      account-db:
        condition: service_started
      discovery-server:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

  account-service:
    build: ./account-service
    image: account-service:latest
    container_name: account-service
    restart: no
    ports:
      - "8081:8081"
      - "5006:5006"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
      # Liquibase переменные
      SPRING_LIQUIBASE_URL: jdbc:postgresql://account-db:5432/postgres?currentSchema=account
      SPRING_LIQUIBASE_USERNAME: ${POSTGRES_USER}
      SPRING_LIQUIBASE_PASSWORD: ${POSTGRES_PASSWORD}
      # Реактивное подключение к PostgreSQL
      SPRING_R2DBC_URL: r2dbc:postgresql://account-db:5432/postgres?currentSchema=account
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}
      # Настройки клиентского сервиса для получения токенов из keycloak
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_ID: ${MARKET_CLIENT_ID}
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_SECRET: ${MARKET_CLIENT_SECRET}
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8090/realms/master
    depends_on:
      account-db:
        condition: service_started
      discovery-server:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

  cash-service:
    build: ./cash-service
    image: cash-service:latest
    container_name: cash-service
    restart: no
    ports:
      - "8082:8082"
      - "5007:5007"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007
      # Настройки клиентского сервиса для получения токенов из keycloak
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_ID: ${MARKET_CLIENT_ID}
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_SECRET: ${MARKET_CLIENT_SECRET}
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8090/realms/master
    depends_on:
      account-db:
        condition: service_started
      account-service:
        condition: service_started
      discovery-server:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

  transfer-service:
    build: ./transfer-service
    image: transfer-service:latest
    container_name: transfer-service
    restart: no
    ports:
      - "8083:8083"
      - "5008:5008"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
      # Настройки клиентского сервиса для получения токенов из keycloak
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_ID: ${MARKET_CLIENT_ID}
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_SECRET: ${MARKET_CLIENT_SECRET}
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8090/realms/master
    depends_on:
      account-db:
        condition: service_started
      account-service:
        condition: service_started
      discovery-server:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    image: notification-service:latest
    container_name: notification-service
    restart: no
    ports:
      - "8084:8084"
      - "5009:5009"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009
      # Liquibase переменные
      SPRING_LIQUIBASE_URL: jdbc:postgresql://notification-db:5432/postgres?currentSchema=notification
      SPRING_LIQUIBASE_USERNAME: ${POSTGRES_USER}
      SPRING_LIQUIBASE_PASSWORD: ${POSTGRES_PASSWORD}
      # Реактивное подключение к PostgreSQL
      SPRING_R2DBC_URL: r2dbc:postgresql://notification-db:5432/postgres?currentSchema=notification
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}
      # Настройки клиентского сервиса для получения токенов из keycloak
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_ID: ${MARKET_CLIENT_ID}
      #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MARKET_CLIENT_SECRET: ${MARKET_CLIENT_SECRET}
      #SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8090/realms/master
    depends_on:
      notification-db:
        condition: service_started
      discovery-server:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - app-network

#### Networks ####
networks:
  app-network:
    driver: bridge
  security-network:
    driver: bridge
  monitoring_network:
    driver: bridge
  elk_network:
    driver: bridge

#### Volumes ####
volumes:
  postgres_data:
  redis_data:
  postgres_keycloak_data:
  notification_db_data:
  elasticsearch_data:
    driver: local