spring:
  application:
    name: cash-service
  config:
    import: configserver:http://127.0.0.1:8888
  profiles:
    active: dev
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8090/realms/master # Адрес сервера авторизации для получения токена
#        registration:
#          cash-service: # Описание клиента OAuth2
#            provider: keycloak
#            authorizationGrantType: client_credentials
#            client-id: cash-service
#            client-secret: xElPJbnMIzvxRInMd2d0eGa5rrQf7tvD
#            scope: profile
#            clientAuthenticationMethod: client_secret_post
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/master

server:
  port: 8082

#application:
#  service:
#    account:
#      url: http://localhost:8081