spring:
  application:
    name: cash-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/master

server:
  port: 8082

application:
  service:
    account:
      url: http://localhost:8081