spring:
  application:
    name:
      gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/master
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Автоматическое создание маршрутов на основе serviceId
          lower-case-service-id: true
      routes:
        # Имя маршрута (используется в логах и конфигурации)
        - id: account-service
          # Куда Gateway проксирует запросы, подходящие под предикаты
          # Здесь это account-service
          uri: lb://account-service
          predicates:
            # Все запросы с путём /account-service/** попадут на этот маршрут
            - Path=/account-service/**
          filters:
            # Подключаем кастомный фильтр Token Relay
            # Он берёт JWT и добавляет заголовок Authorization к исходящему запросу
            - name: JwtTokenRelay
            - name: StripPrefix
              args:
                parts: 1
        # Имя маршрута (используется в логах и конфигурации)
        - id: cash-service
          uri: lb://cash-service
          predicates:
            - Path=/cash-service/**
          filters:
            - name: JwtTokenRelay
            - name: StripPrefix
              args:
                parts: 1
        # Имя маршрута (используется в логах и конфигурации)
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/transfer-service/**
          filters:
            - name: JwtTokenRelay
            - name: StripPrefix
              args:
                parts: 1

management:
  zipkin:
    tracing:
      endpoint:  ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1

server:
  port: 9080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    ru.goncharenko.gateway: DEBUG