apiVersion: v1
kind: Service
metadata:
  name: bank-front
  labels:
    app: bank-front
    {{- include "bank-front.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bank-front
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}