apiVersion: v1
kind: Service
metadata:
  name: exchange-generator
  labels:
    app: exchange-generator
    {{- include "exchange-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: exchange-generator
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}