spring:
  application:
    name: account-service
  config:
    import: configserver:http://127.0.0.1:8888
  profiles:
    active: dev
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=account
#    username: postgres
#    password: password
#  liquibase:
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=account
#    user: postgres
#    password: password
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: account
#    liquibase-schema: public
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8090/realms/master # Адрес сервера авторизации для получения токена
#        registration:
#          account-service: # Описание клиента OAuth2
#            provider: keycloak
#            authorizationGrantType: client_credentials
#            client-id: account-service
#            client-secret: hwpSBn4HQdeVUCqZlFr2RjF3ECggNZKV
#            scope: profile
#            clientAuthenticationMethod: client_secret_post
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/master

#application:
#  service:
#    notification:
#      url: http://localhost:8084

server:
  port: 8081