spring:
  application:
    name: bank-front
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/master
        registration:
          bank-front-service: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: authorization_code
            client-id: bank-front-service
            client-secret: Lwdnla3EWnF4Rxqd39S3XxALq1UEzxs0
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"

management:
  zipkin:
    tracing:
      endpoint:  http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Явно укажите URL
    register-with-eureka: true
    fetch-registry: true
    enabled: true  # Явно включите
  instance:
    hostname: localhost
    prefer-ip-address: false  # Измените на false для localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10  # Уменьшите для отладки
    lease-expiration-duration-in-seconds: 30

server:
  port: 8080

application:
  service:
    gateway:
      url: http://localhost:9080
    account:
      url: http://account-service
    cash:
      url: http://cash-service
    transfer:
      url: http://transfer-service
    postLogoutRedirectUri: http://localhost:8080/account