spring:
  application:
    name: bank-front
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/master
        registration:
          bank-front-service: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: authorization_code
            client-id: bank-front-service
            client-secret: Lwdnla3EWnF4Rxqd39S3XxALq1UEzxs0
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"

server:
  port: 8080

application:
  service:
    gateway:
      url: http://localhost:9080
    account:
      url: http://localhost:8081
    cash:
      url: http://localhost:8082
    transfer:
      url: http://localhost:8083
    postLogoutRedirectUri: http://localhost:8080/account