input {
  beats {
    port => 5044
  }
}
filter {
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+dd.MM.YYYY}"
    retry_on_conflict => 3
    action => "index"
  }
}